# SQL CARTO QUERY FUNCTION
# written for PUI2016_Python2

##### This notebook is set up to link as a default to the fb55 account.  To turn in the homework use the same account you used in the lab (hvt201)  and query the database that you were querying in class (citibike_feb_2015)

In [4]:
try:
    import urllib2 as ulib
except ImportError:
    import urllib3 as ulib

try:
    from StringIO import BytesIO as io
except ImportError:
    from io import BytesIO as io

try:
    from urllib import urlencode as urlencode
except ImportError:
    from urllib.parse import urlencode as urlencode
    
try:
    from urllib import urlopen as urlopen
except ImportError:
    from urllib.request import urlopen as urlopen
    
try:
    from urllib2 import HTTPError as HTTPError
except ImportError:
    from urllib.error import HTTPError as HTTPError

import ast
import pandas as pd

In [5]:
# SQL_SOURCE = 'https://fb55.carto.com/api/v2/sql?q='

# # import urllib2
# # import urllib
# # import StringIO
# # import ast
# # import pandas as pd

# def queryCartoDB(query, format='CSV', source=SQL_SOURCE):
#     '''queries carto datasets from a given carto account
#     Arguments: 
#     query - string: a valid sql query string
#     format - outlut format  OPTIONAL (default CSV)
#     source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
#     Returns:
#     the return of the sql query AS A STRING
#     NOTES:
#     designed for the carto API, tested only with CSV return format'''
    
#     data = urllib.urlencode({'format': format, 'q': query})
#     try:
#         response = urllib2.urlopen(source, data)
#     except urllib2.HTTPError, e:
#         raise ValueError('\n'.join(ast.literal_eval(e.readline())['error']))
#     except Exception:
#         raise
#     return response.read()

SyntaxError: invalid syntax (<ipython-input-5-245f18d82c36>, line 23)

In [6]:
API_URL = 'https://fb55.carto.com:443/api/v2/sql?q='

def queryCartoDB(query, formatting = 'CSV', source = API_URL):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    
    data = urlencode({'format': formatting, 'q': query}).encode("utf-8")
    try:
        response = urlopen(source, data)
        return response.read()
    except HTTPError as e:
        raise (ValueError('\n'.join(ast.literal_eval(e.readline())['error'])))
        
def get_data(query):
    try:
        return pd.read_csv(io(queryCartoDB(query)), sep = ',')
    except ValueError as v:
        print (str(v))

In [7]:
test = '''
SELECT *
FROM citibike
'''

In [9]:
get_data(test)

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.994811,NaN,801,2/1/2015 0:00,2/1/2015 0:14,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
1,NaN,-73.985649,NaN,245,2/1/2015 1:03,2/1/2015 1:07,438,St Marks Pl & 1 Ave,40.727791,89,297,E 15 St & 3 Ave,40.734232,-73.986923,20142,Subscriber,1990.0,1
2,NaN,-73.990093,NaN,379,2/1/2015 0:00,2/1/2015 0:07,497,E 17 St & Broadway,40.737050,2,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1
3,NaN,-73.973715,NaN,2474,2/1/2015 0:01,2/1/2015 0:42,281,Grand Army Plaza & Central Park S,40.764397,3,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969.0,2
4,NaN,-74.004704,NaN,818,2/1/2015 0:01,2/1/2015 0:15,2004,6 Ave & Broome St,40.724399,4,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
5,NaN,-73.986317,NaN,544,2/1/2015 0:01,2/1/2015 0:10,323,Lawrence St & Willoughby St,40.692362,5,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957.0,1
6,NaN,-73.953820,NaN,717,2/1/2015 0:02,2/1/2015 0:14,373,Willoughby Ave & Walworth St,40.693317,6,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979.0,1
7,NaN,-73.977225,NaN,1306,2/1/2015 0:04,2/1/2015 0:26,352,W 56 St & 6 Ave,40.763406,7,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983.0,1
8,NaN,-73.989780,NaN,913,2/1/2015 0:04,2/1/2015 0:19,439,E 4 St & 2 Ave,40.726281,8,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955.0,1
9,NaN,-73.994046,NaN,759,2/1/2015 0:04,2/1/2015 0:17,335,Washington Pl & Broadway,40.729039,9,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985.0,2
10,NaN,-74.002638,NaN,585,2/1/2015 0:05,2/1/2015 0:15,284,Greenwich Ave & 8 Ave,40.739017,10,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982.0,1
11,NaN,-74.002638,NaN,581,2/1/2015 0:05,2/1/2015 0:15,284,Greenwich Ave & 8 Ave,40.739017,11,444,Broadway & W 24 St,40.742354,-73.989151,16936,Subscriber,1988.0,2
12,NaN,-73.988084,NaN,204,2/1/2015 0:05,2/1/2015 0:08,498,Broadway & W 32 St,40.748549,12,472,E 32 St & Park Ave,40.745712,-73.981948,21507,Subscriber,1991.0,2
13,NaN,-74.002150,NaN,1169,2/1/2015 0:07,2/1/2015 0:27,368,Carmine St & 6 Ave,40.730386,13,307,Canal St & Rutgers St,40.714275,-73.989900,17456,Subscriber,1982.0,2
14,NaN,-73.984267,NaN,419,2/1/2015 0:07,2/1/2015 0:14,326,E 11 St & 1 Ave,40.729538,14,2012,E 27 St & 1 Ave,40.739445,-73.976806,14679,Subscriber,1990.0,2
15,NaN,-73.998842,NaN,413,2/1/2015 2:41,2/1/2015 2:48,478,11 Ave & W 41 St,40.760301,171,465,Broadway & W 41 St,40.755136,-73.986580,17968,Subscriber,1970.0,1
16,NaN,-73.990741,NaN,527,2/1/2015 0:09,2/1/2015 0:17,285,Broadway & E 14 St,40.734546,15,212,W 16 St & The High Line,40.743349,-74.006818,18978,Subscriber,1977.0,1
17,NaN,-74.002150,NaN,1013,2/1/2015 0:10,2/1/2015 0:27,368,Carmine St & 6 Ave,40.730386,16,488,W 39 St & 9 Ave,40.756458,-73.993722,16496,Subscriber,1968.0,1
18,NaN,-73.977688,NaN,587,2/1/2015 0:13,2/1/2015 0:23,394,E 9 St & Avenue C,40.725213,17,331,Pike St & Monroe St,40.711731,-73.991930,17107,Subscriber,1990.0,1
19,NaN,-73.984267,NaN,525,2/1/2015 0:13,2/1/2015 0:22,326,E 11 St & 1 Ave,40.729538,18,507,E 25 St & 2 Ave,40.739126,-73.979738,16984,Subscriber,1987.0,1
20,NaN,-73.982912,NaN,670,2/1/2015 0:14,2/1/2015 0:26,493,W 45 St & 6 Ave,40.756800,19,305,E 58 St & 3 Ave,40.760958,-73.967245,15997,Subscriber,1980.0,1
21,NaN,-73.981420,NaN,711,2/1/2015 0:15,2/1/2015 0:27,445,E 10 St & Avenue A,40.727408,20,223,W 13 St & 7 Ave,40.737815,-73.999947,21516,Subscriber,1960.0,1
22,NaN,-73.987834,NaN,1559,2/1/2015 0:16,2/1/2015 0:42,428,E 3 St & 1 Ave,40.724677,21,457,Broadway & W 58 St,40.766953,-73.981693,15815,Subscriber,1986.0,1
23,NaN,-73.971879,NaN,683,2/1/2015 0:16,2/1/2015 0:27,228,E 48 St & 3 Ave,40.754601,22,477,W 41 St & 8 Ave,40.756405,-73.990026,18727,Subscriber,1987.0,1
24,NaN,-73.988639,NaN,522,2/1/2015 0:16,2/1/2015 0:24,513,W 56 St & 10 Ave,40.768254,23,488,W 39 St & 9 Ave,40.756458,-73.993722,14982,Subscriber,1969.0,1
25,NaN,-73.979738,NaN,389,2/1/2015 0:16,2/1/2015 0:23,507,E 25 St & 2 Ave,40.739126,24,518,E 39 St & 2 Ave,40.747804,-73.973442,16391,Subscriber,1957.0,1
26,NaN,-73.989780,NaN,276,2/1/2015 0:16,2/1/2015 0:21,439,E 4 St & 2 Ave,40.726281,25,473,Rivington St & Chrystie St,40.721101,-73.991925,15947,Subscriber,1981.0,1
27,NaN,-74.002971,NaN,907,2/1/2015 0:17,2/1/2015 0:32,128,MacDougal St & Prince St,40.727103,26,531,Forsyth St & Broome St,40.718939,-73.992663,16917,Subscriber,1993.0,1
28,NaN,-73.993934,NaN,946,2/1/2015 0:18,2/1/2015 0:33,490,8 Ave & W 33 St,40.751551,27,528,2 Ave & E 31 St,40.742909,-73.977061,15924,Subscriber,1975.0,1
29,NaN,-73.987030,NaN,144,2/1/2015 0:18,2/1/2015 0:21,350,Clinton St & Grand St,40.715595,28,502,Henry St & Grand St,40.714215,-73.981346,21321,Subscriber,1973.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,NaN,-73.987140,NaN,151,2/1/2015 2:40,2/1/2015 2:42,236,St Marks Pl & 2 Ave,40.728419,169,439,E 4 St & 2 Ave,40.726281,-73.989780,19545,Subscriber,1993.0,1
170,NaN,-73.990765,NaN,1859,2/1/2015 2:41,2/1/2015 3:12,293,Lafayette St & E 8 St,40.730287,170,373,Willoughby Ave & Walworth St,40.693317,-73.953820,19834,Subscriber,1976.0,1
171,NaN,-73.992005,NaN,473,2/1/2015 2:45,2/1/2015 2:53,382,University Pl & E 14 St,40.734927,172,358,Christopher St & Greenwich St,40.732916,-74.007114,19473,Subscriber,1995.0,1
172,NaN,-73.994811,NaN,783,2/1/2015 2:46,2/1/2015 2:59,521,8 Ave & W 31 St,40.750450,173,300,Shevchenko Pl & E 7 St,40.728145,-73.990214,17606,Subscriber,1986.0,1
173,NaN,-73.990765,NaN,310,2/1/2015 2:48,2/1/2015 2:53,293,Lafayette St & E 8 St,40.730287,174,317,E 6 St & Avenue B,40.724537,-73.981854,20011,Subscriber,1968.0,1
174,NaN,-73.995653,NaN,400,2/1/2015 2:49,2/1/2015 2:56,250,Lafayette St & Jersey St,40.724561,175,410,Suffolk St & Stanton St,40.720664,-73.985180,20910,Subscriber,1976.0,2
175,NaN,-74.001768,NaN,198,2/1/2015 2:51,2/1/2015 2:54,489,10 Ave & W 28 St,40.750664,176,521,8 Ave & W 31 St,40.750450,-73.994811,19705,Subscriber,1990.0,1
176,NaN,-73.988084,NaN,561,2/1/2015 2:52,2/1/2015 3:01,498,Broadway & W 32 St,40.748549,177,478,11 Ave & W 41 St,40.760301,-73.998842,17010,Subscriber,1977.0,1
177,NaN,-73.984092,NaN,413,2/1/2015 2:57,2/1/2015 3:03,537,Lexington Ave & E 24 St,40.740259,178,433,E 13 St & Avenue A,40.729554,-73.980572,16235,Subscriber,1988.0,1
178,NaN,-73.990026,NaN,668,2/1/2015 3:00,2/1/2015 3:11,477,W 41 St & 8 Ave,40.756405,179,528,2 Ave & E 31 St,40.742909,-73.977061,17881,Subscriber,1992.0,2
179,NaN,-73.976687,NaN,788,2/1/2015 3:05,2/1/2015 3:18,411,E 6 St & Avenue D,40.722281,180,531,Forsyth St & Broome St,40.718939,-73.992663,16202,Subscriber,1954.0,1
180,NaN,-74.005509,NaN,355,2/1/2015 3:05,2/1/2015 3:11,404,9 Ave & W 14 St,40.740583,181,127,Barrow St & Hudson St,40.731724,-74.006744,14589,Subscriber,1989.0,1
181,NaN,-73.990026,NaN,469,2/1/2015 3:06,2/1/2015 3:14,477,W 41 St & 8 Ave,40.756405,182,160,E 37 St & Lexington Ave,40.748238,-73.978311,14937,Subscriber,1985.0,1
182,NaN,-73.981656,NaN,251,2/1/2015 3:11,2/1/2015 3:16,504,1 Ave & E 15 St,40.732219,183,507,E 25 St & 2 Ave,40.739126,-73.979738,16301,Subscriber,1983.0,1
183,NaN,-73.995653,NaN,422,2/1/2015 3:19,2/1/2015 3:26,250,Lafayette St & Jersey St,40.724561,184,150,E 2 St & Avenue C,40.720874,-73.980858,14837,Subscriber,1980.0,1
184,NaN,-73.998102,NaN,383,2/1/2015 3:21,2/1/2015 3:27,161,LaGuardia Pl & W 3 St,40.729170,185,223,W 13 St & 7 Ave,40.737815,-73.999947,14631,Subscriber,1981.0,2
185,NaN,-73.986022,NaN,145,2/1/2015 3:23,2/1/2015 3:25,491,E 24 St & Park Ave S,40.740964,186,546,E 30 St & Park Ave S,40.744449,-73.983035,18287,Subscriber,1984.0,1
186,NaN,-73.988484,NaN,974,2/1/2015 3:26,2/1/2015 3:43,505,6 Ave & W 33 St,40.749013,187,2004,6 Ave & Broome St,40.724399,-74.004704,14574,Subscriber,1985.0,2
187,NaN,-73.985649,NaN,167,2/1/2015 3:26,2/1/2015 3:29,438,St Marks Pl & 1 Ave,40.727791,188,504,1 Ave & E 15 St,40.732219,-73.981656,16436,Subscriber,1984.0,2
188,NaN,-73.999154,NaN,738,2/1/2015 3:28,2/1/2015 3:41,453,W 22 St & 8 Ave,40.744751,189,300,Shevchenko Pl & E 7 St,40.728145,-73.990214,18573,Subscriber,1987.0,1
189,NaN,-74.002638,NaN,398,2/1/2015 3:28,2/1/2015 3:35,284,Greenwich Ave & 8 Ave,40.739017,190,285,Broadway & E 14 St,40.734546,-73.990741,19040,Subscriber,1977.0,1
190,NaN,-73.981948,NaN,148,2/1/2015 3:29,2/1/2015 3:32,472,E 32 St & Park Ave,40.745712,191,472,E 32 St & Park Ave,40.745712,-73.981948,20727,Subscriber,1982.0,1
191,NaN,-73.988900,NaN,585,2/1/2015 3:32,2/1/2015 3:41,483,E 12 St & 3 Ave,40.732233,192,268,Howard St & Centre St,40.719105,-73.999733,21046,Subscriber,1994.0,1
192,NaN,-73.950048,NaN,366,2/1/2015 3:33,2/1/2015 3:39,437,Macon St & Nostrand Ave,40.680983,193,344,Monroe St & Bedford Ave,40.685144,-73.953809,17284,Subscriber,1984.0,1
193,NaN,-73.979955,NaN,401,2/1/2015 3:39,2/1/2015 3:46,393,E 5 St & Avenue C,40.722992,194,403,E 2 St & 2 Ave,40.725029,-73.990697,20358,Subscriber,1983.0,1
194,NaN,-74.003664,NaN,232,2/1/2015 3:41,2/1/2015 3:44,434,9 Ave & W 18 St,40.743174,195,494,W 26 St & 8 Ave,40.747348,-73.997236,17751,Subscriber,1975.0,1
195,NaN,-73.991255,NaN,412,2/1/2015 3:42,2/1/2015 3:49,479,9 Ave & W 45 St,40.760193,196,267,Broadway & W 36 St,40.750977,-73.987654,15185,Subscriber,1988.0,1
196,NaN,-73.999318,NaN,445,2/1/2015 3:44,2/1/2015 3:52,482,W 15 St & 7 Ave,40.739355,197,504,1 Ave & E 15 St,40.732219,-73.981656,18968,Subscriber,1990.0,1
197,NaN,-73.977724,NaN,861,2/1/2015 3:45,2/1/2015 4:00,511,E 14 St & Avenue B,40.729387,198,335,Washington Pl & Broadway,40.729039,-73.994046,17927,Subscriber,1972.0,1
198,NaN,-73.976485,NaN,339,2/1/2015 3:47,2/1/2015 3:53,520,W 52 St & 5 Ave,40.759923,199,153,E 40 St & 5 Ave,40.752062,-73.981632,17389,Subscriber,1963.0,1

# Task 1

#### Sort data by start_station_id, tripduration 
  ####  -Only checking trips with duration <= 3 hours

In [11]:
query = '''
SELECT *
FROM citibike
WHERE tripduration <= 3*3600
Order BY start_station_id, tripduration
'''
get_data(query)

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.978034,NaN,511,2/1/2015 0:50,2/1/2015 0:59,119,Park Ave & St Edwards St,40.696089,75,420,Clermont Ave & Lafayette Ave,40.687645,-73.969689,20792,Subscriber,1982.0,1
1,NaN,-74.002971,NaN,224,2/1/2015 2:28,2/1/2015 2:32,128,MacDougal St & Prince St,40.727103,165,250,Lafayette St & Jersey St,40.724561,-73.995653,15715,Subscriber,1985.0,1
2,NaN,-74.002971,NaN,428,2/1/2015 1:54,2/1/2015 2:02,128,MacDougal St & Prince St,40.727103,142,312,Allen St & E Houston St,40.722055,-73.989111,21462,Subscriber,1983.0,1
3,NaN,-74.002971,NaN,521,2/1/2015 2:29,2/1/2015 2:38,128,MacDougal St & Prince St,40.727103,166,276,Duane St & Greenwich St,40.717488,-74.010455,15023,Subscriber,1965.0,1
4,NaN,-74.002971,NaN,731,2/1/2015 1:11,2/1/2015 1:23,128,MacDougal St & Prince St,40.727103,92,502,Henry St & Grand St,40.714215,-73.981346,19506,Subscriber,1970.0,1
5,NaN,-74.002971,NaN,907,2/1/2015 0:17,2/1/2015 0:32,128,MacDougal St & Prince St,40.727103,26,531,Forsyth St & Broome St,40.718939,-73.992663,16917,Subscriber,1993.0,1
6,NaN,-73.980858,NaN,665,2/1/2015 0:53,2/1/2015 1:04,150,E 2 St & Avenue C,40.720874,81,497,E 17 St & Broadway,40.737050,-73.990093,18344,Subscriber,1984.0,1
7,NaN,-73.997203,NaN,270,2/1/2015 1:22,2/1/2015 1:27,151,Cleveland Pl & Spring St,40.721816,106,2010,Grand St & Greene St,40.721655,-74.002347,19269,Subscriber,1980.0,1
8,NaN,-73.997203,NaN,671,2/1/2015 0:58,2/1/2015 1:09,151,Cleveland Pl & Spring St,40.721816,87,433,E 13 St & Avenue A,40.729554,-73.980572,14706,Subscriber,1989.0,1
9,NaN,-73.997203,NaN,763,2/1/2015 2:25,2/1/2015 2:38,151,Cleveland Pl & Spring St,40.721816,163,476,E 31 St & 3 Ave,40.743943,-73.979661,21554,Subscriber,1980.0,1
10,NaN,-73.996123,NaN,505,2/1/2015 2:14,2/1/2015 2:22,157,Henry St & Atlantic Ave,40.690893,153,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,14712,Subscriber,1985.0,1
11,NaN,-73.998102,NaN,383,2/1/2015 3:21,2/1/2015 3:27,161,LaGuardia Pl & W 3 St,40.729170,185,223,W 13 St & 7 Ave,40.737815,-73.999947,14631,Subscriber,1981.0,2
12,NaN,-73.970325,NaN,261,2/1/2015 1:41,2/1/2015 1:46,164,E 47 St & 2 Ave,40.753231,131,527,E 33 St & 2 Ave,40.744023,-73.976056,16455,Subscriber,1988.0,1
13,NaN,-73.994564,NaN,709,2/1/2015 0:32,2/1/2015 0:44,168,W 18 St & 6 Ave,40.739713,49,489,10 Ave & W 28 St,40.750664,-74.001768,19705,Subscriber,1979.0,1
14,NaN,-73.984427,NaN,489,2/1/2015 0:50,2/1/2015 0:58,173,Broadway & W 49 St,40.760647,76,305,E 58 St & 3 Ave,40.760958,-73.967245,17416,Subscriber,1984.0,1
15,NaN,-73.984427,NaN,505,2/1/2015 0:24,2/1/2015 0:32,173,Broadway & W 49 St,40.760647,42,442,W 27 St & 7 Ave,40.746647,-73.993915,19766,Subscriber,1972.0,1
16,NaN,-74.010434,NaN,89,2/1/2015 0:53,2/1/2015 0:55,195,Liberty St & Broadway,40.709056,82,264,Maiden Ln & Pearl St,40.707065,-74.007319,14677,Subscriber,1972.0,2
17,NaN,-74.006818,NaN,1757,2/1/2015 1:22,2/1/2015 1:51,212,W 16 St & The High Line,40.743349,104,518,E 39 St & 2 Ave,40.747804,-73.973442,18487,Subscriber,1959.0,1
18,NaN,-73.999947,NaN,345,2/1/2015 0:23,2/1/2015 0:29,223,W 13 St & 7 Ave,40.737815,39,293,Lafayette St & E 8 St,40.730287,-73.990765,17105,Subscriber,1993.0,1
19,NaN,-73.999947,NaN,428,2/1/2015 0:36,2/1/2015 0:43,223,W 13 St & 7 Ave,40.737815,58,237,E 11 St & 2 Ave,40.730473,-73.986724,17886,Subscriber,1989.0,1
20,NaN,-73.971879,NaN,683,2/1/2015 0:16,2/1/2015 0:27,228,E 48 St & 3 Ave,40.754601,22,477,W 41 St & 8 Ave,40.756405,-73.990026,18727,Subscriber,1987.0,1
21,NaN,-73.987140,NaN,151,2/1/2015 2:40,2/1/2015 2:42,236,St Marks Pl & 2 Ave,40.728419,169,439,E 4 St & 2 Ave,40.726281,-73.989780,19545,Subscriber,1993.0,1
22,NaN,-73.987140,NaN,676,2/1/2015 1:41,2/1/2015 1:52,236,St Marks Pl & 2 Ave,40.728419,129,454,E 51 St & 1 Ave,40.754557,-73.965930,18198,Subscriber,1986.0,1
23,NaN,-73.986724,NaN,177,2/1/2015 1:23,2/1/2015 1:26,237,E 11 St & 2 Ave,40.730473,108,293,Lafayette St & E 8 St,40.730287,-73.990765,20638,Subscriber,1992.0,1
24,NaN,-73.986724,NaN,208,2/1/2015 1:52,2/1/2015 1:55,237,E 11 St & 2 Ave,40.730473,140,432,E 7 St & Avenue A,40.726218,-73.983799,17886,Subscriber,1985.0,1
25,NaN,-73.986724,NaN,290,2/1/2015 2:14,2/1/2015 2:19,237,E 11 St & 2 Ave,40.730473,154,312,Allen St & E Houston St,40.722055,-73.989111,17925,Subscriber,1988.0,1
26,NaN,-73.986724,NaN,365,2/1/2015 1:42,2/1/2015 1:48,237,E 11 St & 2 Ave,40.730473,133,401,Allen St & Rivington St,40.720196,-73.989978,17661,Subscriber,1973.0,2
27,NaN,-73.986724,NaN,541,2/1/2015 0:36,2/1/2015 0:45,237,E 11 St & 2 Ave,40.730473,56,472,E 32 St & Park Ave,40.745712,-73.981948,21592,Subscriber,1991.0,1
28,NaN,-74.008592,NaN,1122,2/1/2015 1:54,2/1/2015 2:13,238,Bank St & Washington St,40.736197,141,251,Mott St & Prince St,40.723180,-73.994800,14833,Subscriber,1973.0,1
29,NaN,-73.979382,NaN,265,2/1/2015 0:30,2/1/2015 0:35,243,Fulton St & Rockwell Pl,40.688226,47,261,Johnson St & Gold St,40.694749,-73.983625,18324,Subscriber,1984.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,NaN,-73.981918,NaN,1377,2/1/2015 1:44,2/1/2015 2:07,499,Broadway & W 60 St,40.769155,134,475,E 16 St & Irving Pl,40.735243,-73.987586,15230,Subscriber,1960.0,1
169,NaN,-73.971212,NaN,1270,2/1/2015 1:46,2/1/2015 2:08,501,FDR Drive & E 35 St,40.744219,137,223,W 13 St & 7 Ave,40.737815,-73.999947,18853,Subscriber,1974.0,1
170,NaN,-73.987520,NaN,1090,2/1/2015 1:23,2/1/2015 1:42,503,E 20 St & Park Ave,40.738274,107,229,Great Jones St,40.727434,-73.993790,19718,Subscriber,1961.0,1
171,NaN,-73.981656,NaN,234,2/1/2015 1:13,2/1/2015 1:17,504,1 Ave & E 15 St,40.732219,99,2012,E 27 St & 1 Ave,40.739445,-73.976806,15173,Subscriber,1984.0,1
172,NaN,-73.981656,NaN,251,2/1/2015 3:11,2/1/2015 3:16,504,1 Ave & E 15 St,40.732219,183,507,E 25 St & 2 Ave,40.739126,-73.979738,16301,Subscriber,1983.0,1
173,NaN,-73.981656,NaN,275,2/1/2015 1:11,2/1/2015 1:16,504,1 Ave & E 15 St,40.732219,94,507,E 25 St & 2 Ave,40.739126,-73.979738,15327,Subscriber,1985.0,1
174,NaN,-73.981656,NaN,437,2/1/2015 0:38,2/1/2015 0:46,504,1 Ave & E 15 St,40.732219,59,527,E 33 St & 2 Ave,40.744023,-73.976056,17109,Subscriber,1980.0,1
175,NaN,-73.981656,NaN,602,2/1/2015 0:20,2/1/2015 0:30,504,1 Ave & E 15 St,40.732219,30,411,E 6 St & Avenue D,40.722281,-73.976687,21289,Subscriber,1977.0,1
176,NaN,-73.988484,NaN,417,2/1/2015 2:39,2/1/2015 2:46,505,6 Ave & W 33 St,40.749013,168,2021,W 45 St & 8 Ave,40.759291,-73.988597,18130,Subscriber,1967.0,1
177,NaN,-73.988484,NaN,974,2/1/2015 3:26,2/1/2015 3:43,505,6 Ave & W 33 St,40.749013,187,2004,6 Ave & Broome St,40.724399,-74.004704,14574,Subscriber,1985.0,2
178,NaN,-73.979738,NaN,231,2/1/2015 2:28,2/1/2015 2:32,507,E 25 St & 2 Ave,40.739126,164,237,E 11 St & 2 Ave,40.730473,-73.986724,20353,Subscriber,1985.0,1
179,NaN,-73.979738,NaN,389,2/1/2015 0:16,2/1/2015 0:23,507,E 25 St & 2 Ave,40.739126,24,518,E 39 St & 2 Ave,40.747804,-73.973442,16391,Subscriber,1957.0,1
180,NaN,-73.977724,NaN,442,2/1/2015 0:47,2/1/2015 0:55,511,E 14 St & Avenue B,40.729387,69,410,Suffolk St & Stanton St,40.720664,-73.985180,18232,Subscriber,1993.0,1
181,NaN,-73.977724,NaN,861,2/1/2015 3:45,2/1/2015 4:00,511,E 14 St & Avenue B,40.729387,198,335,Washington Pl & Broadway,40.729039,-73.994046,17927,Subscriber,1972.0,1
182,NaN,-73.977724,NaN,1504,2/1/2015 1:50,2/1/2015 2:15,511,E 14 St & Avenue B,40.729387,138,446,W 24 St & 7 Ave,40.744876,-73.995299,15782,Subscriber,1976.0,1
183,NaN,-73.988639,NaN,522,2/1/2015 0:16,2/1/2015 0:24,513,W 56 St & 10 Ave,40.768254,23,488,W 39 St & 9 Ave,40.756458,-73.993722,14982,Subscriber,1969.0,1
184,NaN,-73.994618,NaN,548,2/1/2015 0:28,2/1/2015 0:37,515,W 43 St & 10 Ave,40.760094,45,466,W 25 St & 6 Ave,40.743954,-73.991449,16731,Subscriber,1964.0,1
185,NaN,-73.976485,NaN,339,2/1/2015 3:47,2/1/2015 3:53,520,W 52 St & 5 Ave,40.759923,199,153,E 40 St & 5 Ave,40.752062,-73.981632,17389,Subscriber,1963.0,1
186,NaN,-73.994811,NaN,783,2/1/2015 2:46,2/1/2015 2:59,521,8 Ave & W 31 St,40.750450,173,300,Shevchenko Pl & E 7 St,40.728145,-73.990214,17606,Subscriber,1986.0,1
187,NaN,-73.994811,NaN,801,2/1/2015 0:00,2/1/2015 0:14,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
188,NaN,-73.977061,NaN,497,2/1/2015 2:21,2/1/2015 2:29,528,2 Ave & E 31 St,40.742909,159,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18299,Subscriber,1982.0,1
189,NaN,-73.992663,NaN,285,2/1/2015 0:23,2/1/2015 0:28,531,Forsyth St & Broome St,40.718939,40,403,E 2 St & 2 Ave,40.725029,-73.990697,19261,Subscriber,1966.0,1
190,NaN,-73.992663,NaN,977,2/1/2015 0:23,2/1/2015 0:39,531,Forsyth St & Broome St,40.718939,35,127,Barrow St & Hudson St,40.731724,-74.006744,15706,Subscriber,1984.0,1
191,NaN,-73.984092,NaN,413,2/1/2015 2:57,2/1/2015 3:03,537,Lexington Ave & E 24 St,40.740259,178,433,E 13 St & Avenue A,40.729554,-73.980572,16235,Subscriber,1988.0,1
192,NaN,-73.960241,NaN,918,2/1/2015 0:44,2/1/2015 0:59,539,Metropolitan Ave & Bedford Ave,40.715348,67,372,Franklin Ave & Myrtle Ave,40.694528,-73.958089,18410,Subscriber,1989.0,1
193,NaN,-73.960241,NaN,1101,2/1/2015 0:34,2/1/2015 0:52,539,Metropolitan Ave & Bedford Ave,40.715348,53,261,Johnson St & Gold St,40.694749,-73.983625,14663,Subscriber,1992.0,1
194,NaN,-73.963198,NaN,999,2/1/2015 1:58,2/1/2015 2:14,2002,Wythe Ave & Metropolitan Ave,40.716887,145,307,Canal St & Rutgers St,40.714275,-73.989900,17365,Subscriber,1966.0,1
195,NaN,-74.004704,NaN,818,2/1/2015 0:01,2/1/2015 0:15,2004,6 Ave & Broome St,40.724399,4,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
196,NaN,-73.988597,NaN,469,2/1/2015 1:37,2/1/2015 1:45,2021,W 45 St & 8 Ave,40.759291,124,480,W 53 St & 10 Ave,40.766697,-73.990617,16528,Subscriber,1975.0,1
197,NaN,-73.959206,NaN,1217,2/1/2015 1:22,2/1/2015 1:43,2022,E 59 St & Sutton Pl,40.758491,105,477,W 41 St & 8 Ave,40.756405,-73.990026,15676,Subscriber,1979.0,2

### Only show the top/last 10 records

In [12]:
query = '''
SELECT *
FROM citibike
limit 10
'''
get_data(query)

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.994811,NaN,801,2/1/2015 0:00,2/1/2015 0:14,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978,2
1,NaN,-73.985649,NaN,245,2/1/2015 1:03,2/1/2015 1:07,438,St Marks Pl & 1 Ave,40.727791,89,297,E 15 St & 3 Ave,40.734232,-73.986923,20142,Subscriber,1990,1
2,NaN,-73.990093,NaN,379,2/1/2015 0:00,2/1/2015 0:07,497,E 17 St & Broadway,40.737050,2,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993,1
3,NaN,-73.973715,NaN,2474,2/1/2015 0:01,2/1/2015 0:42,281,Grand Army Plaza & Central Park S,40.764397,3,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969,2
4,NaN,-74.004704,NaN,818,2/1/2015 0:01,2/1/2015 0:15,2004,6 Ave & Broome St,40.724399,4,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985,2
5,NaN,-73.986317,NaN,544,2/1/2015 0:01,2/1/2015 0:10,323,Lawrence St & Willoughby St,40.692362,5,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957,1
6,NaN,-73.953820,NaN,717,2/1/2015 0:02,2/1/2015 0:14,373,Willoughby Ave & Walworth St,40.693317,6,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979,1
7,NaN,-73.977225,NaN,1306,2/1/2015 0:04,2/1/2015 0:26,352,W 56 St & 6 Ave,40.763406,7,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983,1
8,NaN,-73.989780,NaN,913,2/1/2015 0:04,2/1/2015 0:19,439,E 4 St & 2 Ave,40.726281,8,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955,1
9,NaN,-73.994046,NaN,759,2/1/2015 0:04,2/1/2015 0:17,335,Washington Pl & Broadway,40.729039,9,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985,2

#### List all unique start_station_id values

In [15]:
query = '''
SELECT Distinct start_station_id
FROM citibike
'''
## Removing a redundent column by column selection
get_data(query)[['start_station_id']]

     start_station_id
0                 482
1                 483
2                 498
3                 285
4                 195
5                 539
6                 499
7                 453
8                 447
9                 461
10                281
11                401
12                335
13                382
14                267
15               2022
16                327
17                328
18                212
19                383
20                417
21                434
22                449
23                300
24                293
25                223
26                128
27                501
28                433
29                394
..                ...
77                504
78                284
79                119
80                435
81                479
82                477
83                151
84                472
85                325
86                493
87                465
88                368
89                352
90                323
91                236
92               2002
93                276
94                254
95                489
96                520
97                336
98                291
99                432
100               274
101               537
102               444
103               312
104               511
105               228
106               497

[107 rows x 1 columns]

### Count the number of trips

In [16]:
query = '''
SELECT Count(*)
FROM citibike
'''
get_data(query)

   count  Unnamed: 1
0    199         NaN

#### Find the average/min/max trip duration

In [17]:
query = '''
SELECT Avg(tripduration), Max(tripduration), Min(tripduration)
FROM citibike
'''
get_data(query)

          avg    max  min
0  775.527638  35251   89

# Task 2

#### Selecting trips started on Feb-02-2015 only (since no records exist on this date i use 2015-02-01 instead)

In [18]:
query = '''
SELECT *
FROM citibike
WHERE starttime::date = '2015-02-01'
'''

get_data(query)

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.994811,NaN,801,2/1/2015 0:00,2/1/2015 0:14,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
1,NaN,-73.985649,NaN,245,2/1/2015 1:03,2/1/2015 1:07,438,St Marks Pl & 1 Ave,40.727791,89,297,E 15 St & 3 Ave,40.734232,-73.986923,20142,Subscriber,1990.0,1
2,NaN,-73.990093,NaN,379,2/1/2015 0:00,2/1/2015 0:07,497,E 17 St & Broadway,40.737050,2,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1
3,NaN,-73.973715,NaN,2474,2/1/2015 0:01,2/1/2015 0:42,281,Grand Army Plaza & Central Park S,40.764397,3,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969.0,2
4,NaN,-74.004704,NaN,818,2/1/2015 0:01,2/1/2015 0:15,2004,6 Ave & Broome St,40.724399,4,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
5,NaN,-73.986317,NaN,544,2/1/2015 0:01,2/1/2015 0:10,323,Lawrence St & Willoughby St,40.692362,5,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957.0,1
6,NaN,-73.953820,NaN,717,2/1/2015 0:02,2/1/2015 0:14,373,Willoughby Ave & Walworth St,40.693317,6,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979.0,1
7,NaN,-73.977225,NaN,1306,2/1/2015 0:04,2/1/2015 0:26,352,W 56 St & 6 Ave,40.763406,7,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983.0,1
8,NaN,-73.989780,NaN,913,2/1/2015 0:04,2/1/2015 0:19,439,E 4 St & 2 Ave,40.726281,8,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955.0,1
9,NaN,-73.994046,NaN,759,2/1/2015 0:04,2/1/2015 0:17,335,Washington Pl & Broadway,40.729039,9,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985.0,2
10,NaN,-74.002638,NaN,585,2/1/2015 0:05,2/1/2015 0:15,284,Greenwich Ave & 8 Ave,40.739017,10,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982.0,1
11,NaN,-74.002638,NaN,581,2/1/2015 0:05,2/1/2015 0:15,284,Greenwich Ave & 8 Ave,40.739017,11,444,Broadway & W 24 St,40.742354,-73.989151,16936,Subscriber,1988.0,2
12,NaN,-73.988084,NaN,204,2/1/2015 0:05,2/1/2015 0:08,498,Broadway & W 32 St,40.748549,12,472,E 32 St & Park Ave,40.745712,-73.981948,21507,Subscriber,1991.0,2
13,NaN,-74.002150,NaN,1169,2/1/2015 0:07,2/1/2015 0:27,368,Carmine St & 6 Ave,40.730386,13,307,Canal St & Rutgers St,40.714275,-73.989900,17456,Subscriber,1982.0,2
14,NaN,-73.984267,NaN,419,2/1/2015 0:07,2/1/2015 0:14,326,E 11 St & 1 Ave,40.729538,14,2012,E 27 St & 1 Ave,40.739445,-73.976806,14679,Subscriber,1990.0,2
15,NaN,-73.998842,NaN,413,2/1/2015 2:41,2/1/2015 2:48,478,11 Ave & W 41 St,40.760301,171,465,Broadway & W 41 St,40.755136,-73.986580,17968,Subscriber,1970.0,1
16,NaN,-73.990741,NaN,527,2/1/2015 0:09,2/1/2015 0:17,285,Broadway & E 14 St,40.734546,15,212,W 16 St & The High Line,40.743349,-74.006818,18978,Subscriber,1977.0,1
17,NaN,-74.002150,NaN,1013,2/1/2015 0:10,2/1/2015 0:27,368,Carmine St & 6 Ave,40.730386,16,488,W 39 St & 9 Ave,40.756458,-73.993722,16496,Subscriber,1968.0,1
18,NaN,-73.977688,NaN,587,2/1/2015 0:13,2/1/2015 0:23,394,E 9 St & Avenue C,40.725213,17,331,Pike St & Monroe St,40.711731,-73.991930,17107,Subscriber,1990.0,1
19,NaN,-73.984267,NaN,525,2/1/2015 0:13,2/1/2015 0:22,326,E 11 St & 1 Ave,40.729538,18,507,E 25 St & 2 Ave,40.739126,-73.979738,16984,Subscriber,1987.0,1
20,NaN,-73.982912,NaN,670,2/1/2015 0:14,2/1/2015 0:26,493,W 45 St & 6 Ave,40.756800,19,305,E 58 St & 3 Ave,40.760958,-73.967245,15997,Subscriber,1980.0,1
21,NaN,-73.981420,NaN,711,2/1/2015 0:15,2/1/2015 0:27,445,E 10 St & Avenue A,40.727408,20,223,W 13 St & 7 Ave,40.737815,-73.999947,21516,Subscriber,1960.0,1
22,NaN,-73.987834,NaN,1559,2/1/2015 0:16,2/1/2015 0:42,428,E 3 St & 1 Ave,40.724677,21,457,Broadway & W 58 St,40.766953,-73.981693,15815,Subscriber,1986.0,1
23,NaN,-73.971879,NaN,683,2/1/2015 0:16,2/1/2015 0:27,228,E 48 St & 3 Ave,40.754601,22,477,W 41 St & 8 Ave,40.756405,-73.990026,18727,Subscriber,1987.0,1
24,NaN,-73.988639,NaN,522,2/1/2015 0:16,2/1/2015 0:24,513,W 56 St & 10 Ave,40.768254,23,488,W 39 St & 9 Ave,40.756458,-73.993722,14982,Subscriber,1969.0,1
25,NaN,-73.979738,NaN,389,2/1/2015 0:16,2/1/2015 0:23,507,E 25 St & 2 Ave,40.739126,24,518,E 39 St & 2 Ave,40.747804,-73.973442,16391,Subscriber,1957.0,1
26,NaN,-73.989780,NaN,276,2/1/2015 0:16,2/1/2015 0:21,439,E 4 St & 2 Ave,40.726281,25,473,Rivington St & Chrystie St,40.721101,-73.991925,15947,Subscriber,1981.0,1
27,NaN,-74.002971,NaN,907,2/1/2015 0:17,2/1/2015 0:32,128,MacDougal St & Prince St,40.727103,26,531,Forsyth St & Broome St,40.718939,-73.992663,16917,Subscriber,1993.0,1
28,NaN,-73.993934,NaN,946,2/1/2015 0:18,2/1/2015 0:33,490,8 Ave & W 33 St,40.751551,27,528,2 Ave & E 31 St,40.742909,-73.977061,15924,Subscriber,1975.0,1
29,NaN,-73.987030,NaN,144,2/1/2015 0:18,2/1/2015 0:21,350,Clinton St & Grand St,40.715595,28,502,Henry St & Grand St,40.714215,-73.981346,21321,Subscriber,1973.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,NaN,-73.987140,NaN,151,2/1/2015 2:40,2/1/2015 2:42,236,St Marks Pl & 2 Ave,40.728419,169,439,E 4 St & 2 Ave,40.726281,-73.989780,19545,Subscriber,1993.0,1
170,NaN,-73.990765,NaN,1859,2/1/2015 2:41,2/1/2015 3:12,293,Lafayette St & E 8 St,40.730287,170,373,Willoughby Ave & Walworth St,40.693317,-73.953820,19834,Subscriber,1976.0,1
171,NaN,-73.992005,NaN,473,2/1/2015 2:45,2/1/2015 2:53,382,University Pl & E 14 St,40.734927,172,358,Christopher St & Greenwich St,40.732916,-74.007114,19473,Subscriber,1995.0,1
172,NaN,-73.994811,NaN,783,2/1/2015 2:46,2/1/2015 2:59,521,8 Ave & W 31 St,40.750450,173,300,Shevchenko Pl & E 7 St,40.728145,-73.990214,17606,Subscriber,1986.0,1
173,NaN,-73.990765,NaN,310,2/1/2015 2:48,2/1/2015 2:53,293,Lafayette St & E 8 St,40.730287,174,317,E 6 St & Avenue B,40.724537,-73.981854,20011,Subscriber,1968.0,1
174,NaN,-73.995653,NaN,400,2/1/2015 2:49,2/1/2015 2:56,250,Lafayette St & Jersey St,40.724561,175,410,Suffolk St & Stanton St,40.720664,-73.985180,20910,Subscriber,1976.0,2
175,NaN,-74.001768,NaN,198,2/1/2015 2:51,2/1/2015 2:54,489,10 Ave & W 28 St,40.750664,176,521,8 Ave & W 31 St,40.750450,-73.994811,19705,Subscriber,1990.0,1
176,NaN,-73.988084,NaN,561,2/1/2015 2:52,2/1/2015 3:01,498,Broadway & W 32 St,40.748549,177,478,11 Ave & W 41 St,40.760301,-73.998842,17010,Subscriber,1977.0,1
177,NaN,-73.984092,NaN,413,2/1/2015 2:57,2/1/2015 3:03,537,Lexington Ave & E 24 St,40.740259,178,433,E 13 St & Avenue A,40.729554,-73.980572,16235,Subscriber,1988.0,1
178,NaN,-73.990026,NaN,668,2/1/2015 3:00,2/1/2015 3:11,477,W 41 St & 8 Ave,40.756405,179,528,2 Ave & E 31 St,40.742909,-73.977061,17881,Subscriber,1992.0,2
179,NaN,-73.976687,NaN,788,2/1/2015 3:05,2/1/2015 3:18,411,E 6 St & Avenue D,40.722281,180,531,Forsyth St & Broome St,40.718939,-73.992663,16202,Subscriber,1954.0,1
180,NaN,-74.005509,NaN,355,2/1/2015 3:05,2/1/2015 3:11,404,9 Ave & W 14 St,40.740583,181,127,Barrow St & Hudson St,40.731724,-74.006744,14589,Subscriber,1989.0,1
181,NaN,-73.990026,NaN,469,2/1/2015 3:06,2/1/2015 3:14,477,W 41 St & 8 Ave,40.756405,182,160,E 37 St & Lexington Ave,40.748238,-73.978311,14937,Subscriber,1985.0,1
182,NaN,-73.981656,NaN,251,2/1/2015 3:11,2/1/2015 3:16,504,1 Ave & E 15 St,40.732219,183,507,E 25 St & 2 Ave,40.739126,-73.979738,16301,Subscriber,1983.0,1
183,NaN,-73.995653,NaN,422,2/1/2015 3:19,2/1/2015 3:26,250,Lafayette St & Jersey St,40.724561,184,150,E 2 St & Avenue C,40.720874,-73.980858,14837,Subscriber,1980.0,1
184,NaN,-73.998102,NaN,383,2/1/2015 3:21,2/1/2015 3:27,161,LaGuardia Pl & W 3 St,40.729170,185,223,W 13 St & 7 Ave,40.737815,-73.999947,14631,Subscriber,1981.0,2
185,NaN,-73.986022,NaN,145,2/1/2015 3:23,2/1/2015 3:25,491,E 24 St & Park Ave S,40.740964,186,546,E 30 St & Park Ave S,40.744449,-73.983035,18287,Subscriber,1984.0,1
186,NaN,-73.988484,NaN,974,2/1/2015 3:26,2/1/2015 3:43,505,6 Ave & W 33 St,40.749013,187,2004,6 Ave & Broome St,40.724399,-74.004704,14574,Subscriber,1985.0,2
187,NaN,-73.985649,NaN,167,2/1/2015 3:26,2/1/2015 3:29,438,St Marks Pl & 1 Ave,40.727791,188,504,1 Ave & E 15 St,40.732219,-73.981656,16436,Subscriber,1984.0,2
188,NaN,-73.999154,NaN,738,2/1/2015 3:28,2/1/2015 3:41,453,W 22 St & 8 Ave,40.744751,189,300,Shevchenko Pl & E 7 St,40.728145,-73.990214,18573,Subscriber,1987.0,1
189,NaN,-74.002638,NaN,398,2/1/2015 3:28,2/1/2015 3:35,284,Greenwich Ave & 8 Ave,40.739017,190,285,Broadway & E 14 St,40.734546,-73.990741,19040,Subscriber,1977.0,1
190,NaN,-73.981948,NaN,148,2/1/2015 3:29,2/1/2015 3:32,472,E 32 St & Park Ave,40.745712,191,472,E 32 St & Park Ave,40.745712,-73.981948,20727,Subscriber,1982.0,1
191,NaN,-73.988900,NaN,585,2/1/2015 3:32,2/1/2015 3:41,483,E 12 St & 3 Ave,40.732233,192,268,Howard St & Centre St,40.719105,-73.999733,21046,Subscriber,1994.0,1
192,NaN,-73.950048,NaN,366,2/1/2015 3:33,2/1/2015 3:39,437,Macon St & Nostrand Ave,40.680983,193,344,Monroe St & Bedford Ave,40.685144,-73.953809,17284,Subscriber,1984.0,1
193,NaN,-73.979955,NaN,401,2/1/2015 3:39,2/1/2015 3:46,393,E 5 St & Avenue C,40.722992,194,403,E 2 St & 2 Ave,40.725029,-73.990697,20358,Subscriber,1983.0,1
194,NaN,-74.003664,NaN,232,2/1/2015 3:41,2/1/2015 3:44,434,9 Ave & W 18 St,40.743174,195,494,W 26 St & 8 Ave,40.747348,-73.997236,17751,Subscriber,1975.0,1
195,NaN,-73.991255,NaN,412,2/1/2015 3:42,2/1/2015 3:49,479,9 Ave & W 45 St,40.760193,196,267,Broadway & W 36 St,40.750977,-73.987654,15185,Subscriber,1988.0,1
196,NaN,-73.999318,NaN,445,2/1/2015 3:44,2/1/2015 3:52,482,W 15 St & 7 Ave,40.739355,197,504,1 Ave & E 15 St,40.732219,-73.981656,18968,Subscriber,1990.0,1
197,NaN,-73.977724,NaN,861,2/1/2015 3:45,2/1/2015 4:00,511,E 14 St & Avenue B,40.729387,198,335,Washington Pl & Broadway,40.729039,-73.994046,17927,Subscriber,1972.0,1
198,NaN,-73.976485,NaN,339,2/1/2015 3:47,2/1/2015 3:53,520,W 52 St & 5 Ave,40.759923,199,153,E 40 St & 5 Ave,40.752062,-73.981632,17389,Subscriber,1963.0,1

### Selecting trips started on the weekends

In [20]:
query = '''
SELECT *
FROM citibike
WHERE EXTRACT(DOW FROM starttime::TIMESTAMP) in (0,6)
'''

get_data(query)

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.994811,NaN,801,2/1/2015 0:00,2/1/2015 0:14,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
1,NaN,-73.985649,NaN,245,2/1/2015 1:03,2/1/2015 1:07,438,St Marks Pl & 1 Ave,40.727791,89,297,E 15 St & 3 Ave,40.734232,-73.986923,20142,Subscriber,1990.0,1
2,NaN,-73.990093,NaN,379,2/1/2015 0:00,2/1/2015 0:07,497,E 17 St & Broadway,40.737050,2,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1
3,NaN,-73.973715,NaN,2474,2/1/2015 0:01,2/1/2015 0:42,281,Grand Army Plaza & Central Park S,40.764397,3,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969.0,2
4,NaN,-74.004704,NaN,818,2/1/2015 0:01,2/1/2015 0:15,2004,6 Ave & Broome St,40.724399,4,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
5,NaN,-73.986317,NaN,544,2/1/2015 0:01,2/1/2015 0:10,323,Lawrence St & Willoughby St,40.692362,5,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957.0,1
6,NaN,-73.953820,NaN,717,2/1/2015 0:02,2/1/2015 0:14,373,Willoughby Ave & Walworth St,40.693317,6,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979.0,1
7,NaN,-73.977225,NaN,1306,2/1/2015 0:04,2/1/2015 0:26,352,W 56 St & 6 Ave,40.763406,7,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983.0,1
8,NaN,-73.989780,NaN,913,2/1/2015 0:04,2/1/2015 0:19,439,E 4 St & 2 Ave,40.726281,8,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955.0,1
9,NaN,-73.994046,NaN,759,2/1/2015 0:04,2/1/2015 0:17,335,Washington Pl & Broadway,40.729039,9,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985.0,2
10,NaN,-74.002638,NaN,585,2/1/2015 0:05,2/1/2015 0:15,284,Greenwich Ave & 8 Ave,40.739017,10,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982.0,1
11,NaN,-74.002638,NaN,581,2/1/2015 0:05,2/1/2015 0:15,284,Greenwich Ave & 8 Ave,40.739017,11,444,Broadway & W 24 St,40.742354,-73.989151,16936,Subscriber,1988.0,2
12,NaN,-73.988084,NaN,204,2/1/2015 0:05,2/1/2015 0:08,498,Broadway & W 32 St,40.748549,12,472,E 32 St & Park Ave,40.745712,-73.981948,21507,Subscriber,1991.0,2
13,NaN,-74.002150,NaN,1169,2/1/2015 0:07,2/1/2015 0:27,368,Carmine St & 6 Ave,40.730386,13,307,Canal St & Rutgers St,40.714275,-73.989900,17456,Subscriber,1982.0,2
14,NaN,-73.984267,NaN,419,2/1/2015 0:07,2/1/2015 0:14,326,E 11 St & 1 Ave,40.729538,14,2012,E 27 St & 1 Ave,40.739445,-73.976806,14679,Subscriber,1990.0,2
15,NaN,-73.998842,NaN,413,2/1/2015 2:41,2/1/2015 2:48,478,11 Ave & W 41 St,40.760301,171,465,Broadway & W 41 St,40.755136,-73.986580,17968,Subscriber,1970.0,1
16,NaN,-73.990741,NaN,527,2/1/2015 0:09,2/1/2015 0:17,285,Broadway & E 14 St,40.734546,15,212,W 16 St & The High Line,40.743349,-74.006818,18978,Subscriber,1977.0,1
17,NaN,-74.002150,NaN,1013,2/1/2015 0:10,2/1/2015 0:27,368,Carmine St & 6 Ave,40.730386,16,488,W 39 St & 9 Ave,40.756458,-73.993722,16496,Subscriber,1968.0,1
18,NaN,-73.977688,NaN,587,2/1/2015 0:13,2/1/2015 0:23,394,E 9 St & Avenue C,40.725213,17,331,Pike St & Monroe St,40.711731,-73.991930,17107,Subscriber,1990.0,1
19,NaN,-73.984267,NaN,525,2/1/2015 0:13,2/1/2015 0:22,326,E 11 St & 1 Ave,40.729538,18,507,E 25 St & 2 Ave,40.739126,-73.979738,16984,Subscriber,1987.0,1
20,NaN,-73.982912,NaN,670,2/1/2015 0:14,2/1/2015 0:26,493,W 45 St & 6 Ave,40.756800,19,305,E 58 St & 3 Ave,40.760958,-73.967245,15997,Subscriber,1980.0,1
21,NaN,-73.981420,NaN,711,2/1/2015 0:15,2/1/2015 0:27,445,E 10 St & Avenue A,40.727408,20,223,W 13 St & 7 Ave,40.737815,-73.999947,21516,Subscriber,1960.0,1
22,NaN,-73.987834,NaN,1559,2/1/2015 0:16,2/1/2015 0:42,428,E 3 St & 1 Ave,40.724677,21,457,Broadway & W 58 St,40.766953,-73.981693,15815,Subscriber,1986.0,1
23,NaN,-73.971879,NaN,683,2/1/2015 0:16,2/1/2015 0:27,228,E 48 St & 3 Ave,40.754601,22,477,W 41 St & 8 Ave,40.756405,-73.990026,18727,Subscriber,1987.0,1
24,NaN,-73.988639,NaN,522,2/1/2015 0:16,2/1/2015 0:24,513,W 56 St & 10 Ave,40.768254,23,488,W 39 St & 9 Ave,40.756458,-73.993722,14982,Subscriber,1969.0,1
25,NaN,-73.979738,NaN,389,2/1/2015 0:16,2/1/2015 0:23,507,E 25 St & 2 Ave,40.739126,24,518,E 39 St & 2 Ave,40.747804,-73.973442,16391,Subscriber,1957.0,1
26,NaN,-73.989780,NaN,276,2/1/2015 0:16,2/1/2015 0:21,439,E 4 St & 2 Ave,40.726281,25,473,Rivington St & Chrystie St,40.721101,-73.991925,15947,Subscriber,1981.0,1
27,NaN,-74.002971,NaN,907,2/1/2015 0:17,2/1/2015 0:32,128,MacDougal St & Prince St,40.727103,26,531,Forsyth St & Broome St,40.718939,-73.992663,16917,Subscriber,1993.0,1
28,NaN,-73.993934,NaN,946,2/1/2015 0:18,2/1/2015 0:33,490,8 Ave & W 33 St,40.751551,27,528,2 Ave & E 31 St,40.742909,-73.977061,15924,Subscriber,1975.0,1
29,NaN,-73.987030,NaN,144,2/1/2015 0:18,2/1/2015 0:21,350,Clinton St & Grand St,40.715595,28,502,Henry St & Grand St,40.714215,-73.981346,21321,Subscriber,1973.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,NaN,-73.987140,NaN,151,2/1/2015 2:40,2/1/2015 2:42,236,St Marks Pl & 2 Ave,40.728419,169,439,E 4 St & 2 Ave,40.726281,-73.989780,19545,Subscriber,1993.0,1
170,NaN,-73.990765,NaN,1859,2/1/2015 2:41,2/1/2015 3:12,293,Lafayette St & E 8 St,40.730287,170,373,Willoughby Ave & Walworth St,40.693317,-73.953820,19834,Subscriber,1976.0,1
171,NaN,-73.992005,NaN,473,2/1/2015 2:45,2/1/2015 2:53,382,University Pl & E 14 St,40.734927,172,358,Christopher St & Greenwich St,40.732916,-74.007114,19473,Subscriber,1995.0,1
172,NaN,-73.994811,NaN,783,2/1/2015 2:46,2/1/2015 2:59,521,8 Ave & W 31 St,40.750450,173,300,Shevchenko Pl & E 7 St,40.728145,-73.990214,17606,Subscriber,1986.0,1
173,NaN,-73.990765,NaN,310,2/1/2015 2:48,2/1/2015 2:53,293,Lafayette St & E 8 St,40.730287,174,317,E 6 St & Avenue B,40.724537,-73.981854,20011,Subscriber,1968.0,1
174,NaN,-73.995653,NaN,400,2/1/2015 2:49,2/1/2015 2:56,250,Lafayette St & Jersey St,40.724561,175,410,Suffolk St & Stanton St,40.720664,-73.985180,20910,Subscriber,1976.0,2
175,NaN,-74.001768,NaN,198,2/1/2015 2:51,2/1/2015 2:54,489,10 Ave & W 28 St,40.750664,176,521,8 Ave & W 31 St,40.750450,-73.994811,19705,Subscriber,1990.0,1
176,NaN,-73.988084,NaN,561,2/1/2015 2:52,2/1/2015 3:01,498,Broadway & W 32 St,40.748549,177,478,11 Ave & W 41 St,40.760301,-73.998842,17010,Subscriber,1977.0,1
177,NaN,-73.984092,NaN,413,2/1/2015 2:57,2/1/2015 3:03,537,Lexington Ave & E 24 St,40.740259,178,433,E 13 St & Avenue A,40.729554,-73.980572,16235,Subscriber,1988.0,1
178,NaN,-73.990026,NaN,668,2/1/2015 3:00,2/1/2015 3:11,477,W 41 St & 8 Ave,40.756405,179,528,2 Ave & E 31 St,40.742909,-73.977061,17881,Subscriber,1992.0,2
179,NaN,-73.976687,NaN,788,2/1/2015 3:05,2/1/2015 3:18,411,E 6 St & Avenue D,40.722281,180,531,Forsyth St & Broome St,40.718939,-73.992663,16202,Subscriber,1954.0,1
180,NaN,-74.005509,NaN,355,2/1/2015 3:05,2/1/2015 3:11,404,9 Ave & W 14 St,40.740583,181,127,Barrow St & Hudson St,40.731724,-74.006744,14589,Subscriber,1989.0,1
181,NaN,-73.990026,NaN,469,2/1/2015 3:06,2/1/2015 3:14,477,W 41 St & 8 Ave,40.756405,182,160,E 37 St & Lexington Ave,40.748238,-73.978311,14937,Subscriber,1985.0,1
182,NaN,-73.981656,NaN,251,2/1/2015 3:11,2/1/2015 3:16,504,1 Ave & E 15 St,40.732219,183,507,E 25 St & 2 Ave,40.739126,-73.979738,16301,Subscriber,1983.0,1
183,NaN,-73.995653,NaN,422,2/1/2015 3:19,2/1/2015 3:26,250,Lafayette St & Jersey St,40.724561,184,150,E 2 St & Avenue C,40.720874,-73.980858,14837,Subscriber,1980.0,1
184,NaN,-73.998102,NaN,383,2/1/2015 3:21,2/1/2015 3:27,161,LaGuardia Pl & W 3 St,40.729170,185,223,W 13 St & 7 Ave,40.737815,-73.999947,14631,Subscriber,1981.0,2
185,NaN,-73.986022,NaN,145,2/1/2015 3:23,2/1/2015 3:25,491,E 24 St & Park Ave S,40.740964,186,546,E 30 St & Park Ave S,40.744449,-73.983035,18287,Subscriber,1984.0,1
186,NaN,-73.988484,NaN,974,2/1/2015 3:26,2/1/2015 3:43,505,6 Ave & W 33 St,40.749013,187,2004,6 Ave & Broome St,40.724399,-74.004704,14574,Subscriber,1985.0,2
187,NaN,-73.985649,NaN,167,2/1/2015 3:26,2/1/2015 3:29,438,St Marks Pl & 1 Ave,40.727791,188,504,1 Ave & E 15 St,40.732219,-73.981656,16436,Subscriber,1984.0,2
188,NaN,-73.999154,NaN,738,2/1/2015 3:28,2/1/2015 3:41,453,W 22 St & 8 Ave,40.744751,189,300,Shevchenko Pl & E 7 St,40.728145,-73.990214,18573,Subscriber,1987.0,1
189,NaN,-74.002638,NaN,398,2/1/2015 3:28,2/1/2015 3:35,284,Greenwich Ave & 8 Ave,40.739017,190,285,Broadway & E 14 St,40.734546,-73.990741,19040,Subscriber,1977.0,1
190,NaN,-73.981948,NaN,148,2/1/2015 3:29,2/1/2015 3:32,472,E 32 St & Park Ave,40.745712,191,472,E 32 St & Park Ave,40.745712,-73.981948,20727,Subscriber,1982.0,1
191,NaN,-73.988900,NaN,585,2/1/2015 3:32,2/1/2015 3:41,483,E 12 St & 3 Ave,40.732233,192,268,Howard St & Centre St,40.719105,-73.999733,21046,Subscriber,1994.0,1
192,NaN,-73.950048,NaN,366,2/1/2015 3:33,2/1/2015 3:39,437,Macon St & Nostrand Ave,40.680983,193,344,Monroe St & Bedford Ave,40.685144,-73.953809,17284,Subscriber,1984.0,1
193,NaN,-73.979955,NaN,401,2/1/2015 3:39,2/1/2015 3:46,393,E 5 St & Avenue C,40.722992,194,403,E 2 St & 2 Ave,40.725029,-73.990697,20358,Subscriber,1983.0,1
194,NaN,-74.003664,NaN,232,2/1/2015 3:41,2/1/2015 3:44,434,9 Ave & W 18 St,40.743174,195,494,W 26 St & 8 Ave,40.747348,-73.997236,17751,Subscriber,1975.0,1
195,NaN,-73.991255,NaN,412,2/1/2015 3:42,2/1/2015 3:49,479,9 Ave & W 45 St,40.760193,196,267,Broadway & W 36 St,40.750977,-73.987654,15185,Subscriber,1988.0,1
196,NaN,-73.999318,NaN,445,2/1/2015 3:44,2/1/2015 3:52,482,W 15 St & 7 Ave,40.739355,197,504,1 Ave & E 15 St,40.732219,-73.981656,18968,Subscriber,1990.0,1
197,NaN,-73.977724,NaN,861,2/1/2015 3:45,2/1/2015 4:00,511,E 14 St & Avenue B,40.729387,198,335,Washington Pl & Broadway,40.729039,-73.994046,17927,Subscriber,1972.0,1
198,NaN,-73.976485,NaN,339,2/1/2015 3:47,2/1/2015 3:53,520,W 52 St & 5 Ave,40.759923,199,153,E 40 St & 5 Ave,40.752062,-73.981632,17389,Subscriber,1963.0,1

### Apparently there is only one date in the data. Lets see it using query

In [21]:
query = '''
SELECT Distinct starttime::date AS date, EXTRACT(DOW FROM starttime::TIMESTAMP) AS DOW
FROM citibike
'''

get_data(query)

         date  dow
0  2015-02-01    0

#### There is only one date and the corresponding day of the week is sunday.

### What are average trip duration during weekends?

In [22]:
query = '''
SELECT Avg(tripduration) AS AvgTripDuration
FROM citibike
WHERE EXTRACT(DOW FROM starttime::TIMESTAMP) in (0,6)
'''
get_data(query)[['avgtripduration']]

   avgtripduration
0       775.527638

#### Can we do the same for weekday?

In [23]:
query = '''
SELECT Avg(tripduration) AS AvgTripDuration
FROM citibike
WHERE EXTRACT(DOW FROM starttime::TIMESTAMP) in (1,2,3,4,5)
'''
get_data(query)[['avgtripduration']]

   avgtripduration
0              NaN

#### Showing the list of start station locations

In [24]:
query = '''
SELECT Distinct start_station_name
FROM citibike
'''
get_data(query)[['start_station_name']]

                    start_station_name
0                      W 56 St & 6 Ave
1              Bank St & Washington St
2                       E 3 St & 1 Ave
3                      8 Ave & W 52 St
4                    E 6 St & Avenue B
5         Willoughby Ave & Walworth St
6                   E 17 St & Broadway
7                       E 4 St & 2 Ave
8                      W 37 St & 5 Ave
9    Grand Army Plaza & Central Park S
10              W Broadway & Spring St
11                    10 Ave & W 28 St
12            Lafayette St & Jersey St
13                     2 Ave & E 31 St
14                     8 Ave & W 33 St
15            MacDougal St & Prince St
16              Barclay St & Church St
17                  Broadway & W 41 St
18              Forsyth St & Broome St
19                 FDR Drive & E 35 St
20             Allen St & E Houston St
21                     W 13 St & 6 Ave
22                     9 Ave & W 18 St
23                   E 6 St & Avenue D
24                  E 20 St & Park Ave
25                  Broadway & W 49 St
26                     W 18 St & 6 Ave
27                     W 20 St & 7 Ave
28                  Broadway & W 32 St
29                     E 11 St & 2 Ave
..                                 ...
77             Watts St & Greenwich St
78                     6 Ave & W 33 St
79                   E 9 St & Avenue C
80             W 16 St & The High Line
81             Lexington Ave & E 24 St
82                     E 12 St & 3 Ave
83                    W 56 St & 10 Ave
84                     E 19 St & 3 Ave
85                     2 Ave & E 58 St
86                      E 2 St & 2 Ave
87                  E 32 St & Park Ave
88             Macon St & Nostrand Ave
89                   E 5 St & Avenue C
90               Clinton St & Grand St
91                     E 47 St & 2 Ave
92                  Carmine St & 6 Ave
93                   E 7 St & Avenue A
94               Liberty St & Broadway
95               LaGuardia Pl & W 3 St
96                     W 45 St & 8 Ave
97             DeKalb Ave & Hudson Ave
98            Cleveland Pl & Spring St
99          Greenwich Ave & Charles St
100                    E 20 St & 2 Ave
101                    W 21 St & 6 Ave
102                    8 Ave & W 31 St
103       Wythe Ave & Metropolitan Ave
104                    W 11 St & 6 Ave
105                    W 22 St & 8 Ave
106                St Marks Pl & 1 Ave

[107 rows x 1 columns]

#### Showing the number of trips started per station

In [25]:
query = '''
SELECT start_station_name, Count(*)
FROM citibike
Group By start_station_name
'''
get_data(query)

                    start_station_name  count
0                      W 56 St & 6 Ave      1
1              Bank St & Washington St      1
2                       E 3 St & 1 Ave      1
3                      8 Ave & W 52 St      2
4                    E 6 St & Avenue B      3
5         Willoughby Ave & Walworth St      1
6                   E 17 St & Broadway      2
7                       E 4 St & 2 Ave      2
8                      W 37 St & 5 Ave      1
9    Grand Army Plaza & Central Park S      1
10              W Broadway & Spring St      1
11                    10 Ave & W 28 St      1
12            Lafayette St & Jersey St      6
13                     2 Ave & E 31 St      1
14                     8 Ave & W 33 St      2
15            MacDougal St & Prince St      5
16              Barclay St & Church St      1
17                  Broadway & W 41 St      1
18              Forsyth St & Broome St      2
19                 FDR Drive & E 35 St      1
20             Allen St & E Houston St      4
21                     W 13 St & 6 Ave      2
22                     9 Ave & W 18 St      2
23                   E 6 St & Avenue D      1
24                  E 20 St & Park Ave      1
25                  Broadway & W 49 St      2
26                     W 18 St & 6 Ave      1
27                     W 20 St & 7 Ave      1
28                  Broadway & W 32 St      3
29                     E 11 St & 2 Ave      5
..                                 ...    ...
77             Watts St & Greenwich St      2
78                     6 Ave & W 33 St      2
79                   E 9 St & Avenue C      1
80             W 16 St & The High Line      1
81             Lexington Ave & E 24 St      1
82                     E 12 St & 3 Ave      1
83                    W 56 St & 10 Ave      1
84                     E 19 St & 3 Ave      1
85                     2 Ave & E 58 St      2
86                      E 2 St & 2 Ave      2
87                  E 32 St & Park Ave      3
88             Macon St & Nostrand Ave      1
89                   E 5 St & Avenue C      1
90               Clinton St & Grand St      1
91                     E 47 St & 2 Ave      1
92                  Carmine St & 6 Ave      3
93                   E 7 St & Avenue A      1
94               Liberty St & Broadway      1
95               LaGuardia Pl & W 3 St      1
96                     W 45 St & 8 Ave      1
97             DeKalb Ave & Hudson Ave      1
98            Cleveland Pl & Spring St      3
99          Greenwich Ave & Charles St      2
100                    E 20 St & 2 Ave      2
101                    W 21 St & 6 Ave      1
102                    8 Ave & W 31 St      2
103       Wythe Ave & Metropolitan Ave      1
104                    W 11 St & 6 Ave      1
105                    W 22 St & 8 Ave      3
106                St Marks Pl & 1 Ave      4

[107 rows x 2 columns]

#### Trips per station but only for stations within 500m of Time Square! The coordinates of Time Square is (40.7577,-73.9857)

In [26]:
query = '''
Select start_station_name, Count(*)
From citibike
WHERE ST_DWithin(ST_MakePoint(start_station_latitude,start_station_longitude)::geography,
                 ST_GeogFromText('POINT(40.7577 -73.9857)'),
                 500, false)
Group By start_station_name
'''

get_data(query)

    start_station_name  count
0      6 Ave & W 33 St      2
1      8 Ave & W 52 St      2
2   Broadway & W 29 St      1
3   Broadway & W 32 St      3
4   Broadway & W 36 St      1
5   Broadway & W 41 St      1
6   Broadway & W 49 St      2
7      W 37 St & 5 Ave      1
8      W 41 St & 8 Ave      3
9      W 45 St & 6 Ave      1
10     W 45 St & 8 Ave      1
11     W 52 St & 9 Ave      2
12    W 56 St & 10 Ave      1

#### Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare!

In [27]:
query = '''
Select start_station_name, Avg(tripduration)
From citibike
WHERE ST_DWithin(ST_MakePoint(start_station_latitude,start_station_longitude)::geography,
                 ST_GeogFromText('POINT(40.7577 -73.9857)'),
                 500, false)
       AND
      EXTRACT(DOW FROM starttime::TIMESTAMP) in (0,6)               
Group By start_station_name
Order BY Avg(tripduration) Desc
Limit 1
'''

get_data(query)

  start_station_name    avg
0    8 Ave & W 52 St  891.5

#### Extra: create lines for trips started from stations within 500m of Times Squares and lasted less than 2 hours. The number of trips per each pair of stations are output as attributes of these lines.

In [28]:
query = '''
Select ST_MakeLine(ST_MakePoint(start_station_latitude,start_station_longitude),ST_MakePoint(end_station_latitude,end_station_longitude)), COunt(*)
From citibike
WHERE ST_DWithin(ST_MakePoint(start_station_latitude,start_station_longitude)::geography,
                 ST_GeogFromText('POINT(40.7577 -73.9857)'),
                 500, false)   
                 AND
      tripduration < 2*3600
Group By ST_MakeLine(ST_MakePoint(start_station_latitude,start_station_longitude),ST_MakePoint(end_station_latitude,end_station_longitude))
'''

get_data(query)

                                          st_makeline  count
0   01020000000200000021994848A8604440BE51C821247F...      1
1   010200000002000000BE8E0FE5D1604440B9CBD9965C7F...      1
2   010200000002000000D72EF170D05F4440523958C53C7F...      1
3   01020000000200000082DE02A6DF5F4440BD772F52437F...      1
4   0102000000020000004D0F6D740C60444050741BDCEF7E...      1
5   010200000002000000D72EF170D05F4440523958C53C7F...      1
6   010200000002000000BBE1EB29C1614440D0F1D1E20C7F...      1
7   01020000000200000075DFD682835F4440C2448B85447F...      1
8   010200000002000000BE8E0FE5D1604440B9CBD9965C7F...      1
9   010200000002000000058E5FD3DE604440860DC305E87E...      1
10  010200000002000000BBE1EB29C1614440D0F1D1E20C7F...      1
11  010200000002000000BF6DBFDF5C614440385762D8007F...      1
12  010200000002000000BF6DBFDF5C614440385762D8007F...      1
13  01020000000200000082DE02A6DF5F4440BD772F52437F...      1
14  0102000000020000004FBF970420604440AF164CBA357F...      1
15  010200000002000000D72EF170D05F4440523958C53C7F...      1
16  010200000002000000BE8E0FE5D1604440B9CBD9965C7F...      1
17  0102000000020000003BF8917430614440F1D84B2A457F...      1
18  010200000002000000B682A62556624440362383DC457F...      1
19  0102000000020000001189C603DF614440684FD1AA397F...      1
20  0102000000020000001189C603DF614440684FD1AA397F...      1

# extra credit: make the function python 2 and 3 compatible so that it works on the  PUI2016_Python3 kernel